### ISSUE TITLE
Bit of a dumb question buuuuttt

### ISSUE THREAD

**Issue by GhostieSpook** [3Nya3/Shiro-Bot#2]
What are all the commands Shiro has? I wanna check the bot out for my NGNL style server.

**Comment by 3Nya3** [comment]
Haha the bot doesn't have many commands atm since I'm working on my uni stuff and other projects, but I'm happy to help you get a custom bot up for your server if you need one. You can DM me at 
`Zyuile 「白根あらし」#0001`
